<a href="https://colab.research.google.com/github/StrizhAXE/LineAlgebra/blob/main/Les_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###1. Part 1

__1.__ Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:



а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

Колличество строк А не равно количеству столбцов В, произведение не определено.

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

Колличество строк А не равно количеству столбцов В, не произведение определено.

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

Колличество строк А равно количеству столбцов В, произведение определено. Размерность А * В = 8 х 8

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .

Колличество строк А равно количеству столбцов В, произведение определено. Размерность А * В = 4 х 4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [8]:
import numpy as np
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

c = a + b
d = a.dot(b)
print(f"Сумма a + b = \n{c}\n")
print(f"Произведение a * b = \n{d}\n")


Сумма a + b = 
[[ 5 -3]
 [ 3  5]]

Произведение a * b = 
[[  4 -11]
 [ 12  -3]]



__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [10]:
a = np.array([[1, 7], [3, 6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

d = 3 * a - 2 * b + 4 * c
print(f"3A − 2B + 4C = \n{d}\n")

3A − 2B + 4C = 
[[11 -5]
 [ 9 24]]



__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [12]:
a = np.array([[4, 7], [5, -2], [2, 3]])
aT = a.T
c = a@aT
d = aT@a
print(f"a = \n {a}")
print(f"aT = \n {aT}")
print(f"a * aT = \n {c}")
print(f"aT * a= \n {d}")

a = 
 [[ 4  7]
 [ 5 -2]
 [ 2  3]]
aT = 
 [[ 4  5  2]
 [ 7 -2  3]]
a * aT = 
 [[65  6 29]
 [ 6 29  4]
 [29  4 13]]
aT * a= 
 [[45 24]
 [24 62]]


###2. Part 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

detA=|A|=sin(x)**2 + cos(x)**2 = 1



   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

detA=|A|=4 * 5 * 9 = 180    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

   Пока решения нет
  